### ISSUE TITLE
How to access the website?

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/zeronet_ynh#4]
I have created a new website but as the app is behind SSO it can not be accessed. Is this done for the security reasons? If yes how can I access my website till I don't have any other peer?

**Comment by whypsi** [comment]
The SSO is on purpose, otherwise other users could access and temper with your site content.

As I understand content is served via port 15441. HTTPS (443) is only used to connect to the Zeronet UserInterface (where you can browser other sites but also manage your content). So to become a proper serving Zeronet peer you need to make sure port 15441 UDP is open (forwarded). If I'm not mistaken one could set up Tor hidden service as an alternative though I haven't personally tried that.
